version: "3"
services:
  das:
    image: "trydas/sustainability:latest"
    depends_on:
      - redis
    networks:
      - das-net
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  redis:
    image: "redis:latest"
    restart: always
    networks:
      - das-net
  nginx:
    build:
      context: ./nginx
    restart: always
    depends_on:
      - das
    ports:
      - "80:80"
    networks:
      - das-net
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

networks:
  das-net:
